sudo: required

dist: trusty

language: node_js

node_js:
  - "0.10"
  - "4"
  - "6"
  - "8"

# Undo `_JAVA_OPTIONS` environment variable;
# see https://github.com/travis-ci/travis-ci/issues/8408
before_script:
  - _JAVA_OPTIONS=

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
