sudo: required
dist: trusty

language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"

install:
  - npm install -g grunt-cli
  - grunt --version
  - npm install

script:
  - npm test

matrix:
  fast_finish: true
