sudo: false

language: java

env:
  - NODE_VERSION=0.10
  - NODE_VERSION=4
  - NODE_VERSION=5

jdk:
  - oraclejdk8

before_install:
  - nvm install "$NODE_VERSION"
  - node --version
  - npm --version
  - java -version

install:
  - npm install -g grunt-cli
  - grunt --version
  - npm install

script:
  - npm test

matrix:
  fast_finish: true
